server:
  address: localhost
  port: 8080

spring:
  datasource:
    username: guest
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witherview?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate: error

---

spring:
  profiles: test
  datasource:
    username: guest
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witherview_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
