server:
  port: 8080
  host: localhost
  url: http://localhost:8080/

upload:
  location: /root/videos/

ffmpeg:
  path: /root/ffmpeg_sources/ffmpeg/

spring:
  datasource:
    username: guest
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witherview?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

logging:
  level:
    org.hibernate: error

---

spring:
  profiles: test
  datasource:
    username: guest
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witherview_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
